"""empty message

Revision ID: fbff400db65b
Revises: 24825250c3ba
Create Date: 2022-12-01 21:37:55.976149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbff400db65b'
down_revision = '24825250c3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite_Characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'characters_id')
    )
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('Favorite_Characters')
    # ### end Alembic commands ###
